image: python:3.7

stages:
  - deploy

deploy_job:
  cache: {}
  stage: deploy
  script:
    - pip3 install -U fandogh-cli
    - COLLECT_ERROR=True fandogh login --username $FANDOGH_USERNAME --password $FANDOGH_PASSWORD
    - touch .env
    - echo "BOT_TOKEN=\"$APP_BOT_TOKEN\"" >> .env
    - echo "DB_URI=\"$APP_DB_URI\"" >> .env
    - fandogh namespace active --name=archlinux
    - fandogh image init --name archie_bot
    - fandogh image publish -v $CI_COMMIT_SHORT_SHA
    - fandogh service apply -f fandogh.manifest.yaml -p VERSION=$CI_COMMIT_SHORT_SHA
  when: always
  only:
    - master