image: python:3.7

stages:
  - deploy

deploy_job:
  stage: deploy
  script:
    - pip3 install -U fandogh-cli
    - fandogh login --username $FANDOGH_USERNAME --password $FANDOGH_PASSWORD
    - echo "BOT_TOKEN=\"$APP_BOT_TOKEN\"\nDB_URI=\"$APP_DB_URI\"" > .env
    - fandogh image publish -v head
  when: manual