image: python:3.7

stages:
  - deploy

deploy_job:
  stage: deploy
  script:
    - pip3 install -U fandogh-cli
    - COLLECT_ERROR=True fandogh login --username $FANDOGH_USERNAME --password $FANDOGH_PASSWORD
    - touch .env
    - echo "BOT_TOKEN=\"$APP_BOT_TOKEN\"" >> .env
    - echo "DB_URI=\"$APP_DB_URI\"" >> .env
    - fandogh namespace active --name=archlinux
    - fandogh image init --name archie_bot
    - fandogh image publish -v $CI_COMMIT_SHORT_SHA
    - fandogh service deploy --image archie_bot --version $CI_COMMIT_SHORT_SHA --name archie-bot --env DB_URI="$APP_DB_URI" --env BOT_TOKEN="$APP_BOT_TOKEN"
  when: always